[theme]
base = "light"
primaryColor = "#3697b3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#1f2328"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
